

#define ARROW_VERSION 0
#define ARROW_VERSION_MAJOR 7
#define ARROW_VERSION_MINOR 0
#define ARROW_VERSION_PATCH 0
#define ARROW_VERSION_STRING "7.0.0"
#define ARROW_SO_VERSION ""
#define ARROW_FULL_SO_VERSION ""
#define ARROW_CXX_COMPILER_ID ""
#define ARROW_CXX_COMPILER_VERSION ""
#define ARROW_CXX_COMPILER_FLAGS ""
#define ARROW_GIT_ID ""
#define ARROW_GIT_DESCRIPTION ""
#define ARROW_PACKAGE_KIND ""
#define ARROW_BUILD_TYPE "inadvisable"

